#ifndef NODE_TYPE_H
#define NODE_TYPE_H

enum node_type
{
    NODE_ROOT = 0,
    NODE_INPUT,
    NODE_LIST,
    NODE_AND_OR,
    NODE_PIPELINE,
    NODE_COMMAND,
    NODE_SIMPLE_COMMAND,
    NODE_SHELL_COMMAND,
    NODE_RULE_IF,
    NODE_COMPOUND_LIST,
    NODE_IONUMBER,

    NODE_REDIRECT_OUTPUT,
    NODE_REDIRECT_INPUT,
    NODE_REDIRECT_APPEND_OUTPUT,
    NODE_REDIRECT_DUP_INPUT,
    NODE_REDIRECT_DUP_OUTPUT,
    NODE_REDIRECT_RDWR,
    NODE_ASSIGNEMENT_WORD,

    NODE_LIST_REDIRECTION,
    NODE_LIST_ASSIGNEMENT,
    NODE_LIST_WORD,
    NODE_ELSE_CLAUSE,
    NODE_FUNCDEC,
    NODE_DO,
    NODE_WHILE,
    NODE_UNTIL,
    NODE_CASE_ITEM,
    NODE_CASE_CLAUSE,
    NODE_RULE_CASE,
    NODE_FOR,
    NODE_OTHER,
    NODE_WORD,

};

#endif // NODE_TYPE_H
