.TH 42SH "December 2020" 42SH

.SH NAME
.P
42sh \- 42Lanta

.SH AUTHORS
.P

\- Arthur Fan \fBarthur.fan\fR\fI@\fR\fBepita.fr\fR

\- Pierre-Louis Landouzi \fBpierre-louis.landouzi\fR\fI@\fR\fBepita.fr\fR

\- Hao Ye \fBhao.ye\fR\fI@\fR\fBepita.fr\fR

\- Karim Salhi \fBkarim.salhi\fR\fI@\fR\fBepita.fr\fR

.SH SYNOPSIS
.P
\fB42sh\fR [\fIOPTIONS\fR] [\fIFILE\fR]

.SH DESCRIPTION
.P
\fB42sh\fR is an \fBsh\fR-compatible command language interpreter that
executes commands read from the standard input or from a file.
